/*
 * generated by Xtext 2.11.0
 */
package glt.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import robotDSL.ui.internal.RobotDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RobotDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RobotDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RobotDSLActivator.getInstance().getInjector(RobotDSLActivator.GLT_ROBOTDSL);
	}
	
}
