/**
 * generated by Xtext 2.11.0
 */
package glt;

import glt.AbstractRobotDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RobotDSLRuntimeModule extends AbstractRobotDSLRuntimeModule {
}
