/*Generated by MPS */


public class Cell {
  private int marks = 0;
  private boolean wall = false;
  private boolean robot = false;
  public Cell(boolean wall) {
    this.wall = wall;
  }
  public void setRobot() {
    if (wall) {
      throw new RuntimeException("robot cannot be placed on a wall.");
    }
    robot = true;
  }
  public void unsetRobot() {
    robot = false;
  }
  public boolean isRobot() {
    return robot;
  }
  public void setWall() {
    wall = true;
  }
  public void unsetWall() {
    wall = false;
  }
  public boolean isWall() {
    return wall;
  }
  public void addMark() {
    marks++;
  }
  public void removeMark() {
    marks--;
  }
  public int getMarks() {
    return marks;
  }
}
