/*
 * generated by Xtext 2.11.0
 */
package glt.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotDSLScopeProvider extends DelegatingScopeProvider {
}
