/**
 * generated by Xtext 2.11.0
 */
package glt.ui;

import glt.ui.AbstractRobotDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RobotDSLUiModule extends AbstractRobotDSLUiModule {
  public RobotDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
