/*
 * generated by Xtext 2.11.0
 */
package glt.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import robotDSL.ui.internal.RobotDSLActivator;

public class RobotDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotDSLActivator.getInstance().getInjector("glt.RobotDSL");
	}

}
