/*
 * generated by Xtext 2.11.0
 */
package glt.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import robotDSLEcore.Script

@RunWith(XtextRunner)
@InjectWith(RobotDSLInjectorProvider)
class RobotDSLParsingTest {
	@Inject
	ParseHelper<Script> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
