/**
 * generated by Xtext 2.11.0
 */
package glt.validation;

import glt.validation.AbstractRobotDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RobotDSLValidator extends AbstractRobotDSLValidator {
}
