/**
 * generated by Xtext 2.11.0
 */
package glt.ui.contentassist;

import glt.ui.contentassist.AbstractRobotDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RobotDSLProposalProvider extends AbstractRobotDSLProposalProvider {
}
