/*
 * generated by Xtext 2.11.0
 */
package glt.ide

import com.google.inject.Guice
import glt.RobotDSLRuntimeModule
import glt.RobotDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RobotDSLIdeSetup extends RobotDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RobotDSLRuntimeModule, new RobotDSLIdeModule))
	}
	
}
